### ISSUE TITLE
Remove pybossa hook

### ISSUE THREAD

**Issue by ppeczek** [themoonsheep/moonsheep#102]
Right now when pybossa collects enough taskruns it calls a webhook in moonsheep. The webhook verifies and saves data. If anything goes wrong, data is actually lost - it is still in pybossa, never called again, and moonsheep is not aware of it.

**Comment by ppeczek** [comment]
Maybe there should be reserved field in moonsheep task, "verified", which is set to true if webhook verifies successfully task. Otherwise it will be sent to manual verification OR in future to re-verify

**Comment by KrzysztofMadejski** [comment]
Repivoting because we are moving away from pybossa #116
