### ISSUE TITLE
Structured data export

### ISSUE THREAD

**Issue by pisipite** [themoonsheep/moonsheep#48]
to be able to export the data into different formats.
- csv+frictionless data
- Direkt36 or other special formats

**Comment by KrzysztofMadejski** [comment]
Acceptance Criteria:
- [ ] frictionless data output
- [ ] Guidelines on how to write your own exporter

**Comment by KrzysztofMadejski** [comment]
To implement API there are some libraries mentioned here: https://github.com/humiaozuzu/awesome-flask

**Comment by KrzysztofMadejski** [comment]
Ideally models should be registered with moonsheep and everything else should work out of the box.

```python
from django.db import models
from moonsheep import register

@register.model
class Declaration(models.Model):
     ...
```

Effect: 
- JSON-API compliant API generated at http://your.domain/api/declaration
- Excel export outputting a spreadsheet containing as many sheets as there are models defined

**Comment by KrzysztofMadejski** [comment]
@catileptic I'm working on it now.

**Comment by KrzysztofMadejski** [comment]
Implementing an API for domain model is as simple as:
```python
from moonsheep.api import AppApi
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^moonsheep/', include('moonsheep.urls')),
    # ...
  
    url(r'^api/opora/', AppApi('opora').urls),
]
```

`AppApi` scans for all domain models defined in your app (passed in the param) and generates URL for each using Django Rest Framework. Rest Framework gives you a nice html interface to play with requests, discovery (listing of all endpoints). Using moonsheep-opora example: http://localhost:8000/api/opora/

![api-generated](https://user-images.githubusercontent.com/849975/67669956-2e9b5d80-f973-11e9-88dd-3c8cb7392636.png)
