### ISSUE TITLE
Automatic Form Generation

### ISSUE THREAD

**Issue by IronRunes** [themoonsheep/moonsheep#64]

**Comment by KrzysztofMadejski** [comment]
Acceptance Criteria:
- [ ] Command line script that generates default html form based on data model
- [ ] Generated form shouldn't be overwritten when older exists

**Comment by KrzysztofMadejski** [comment]
Small research notes, CC @georgeslabreche :
- WTForms supports form validation and form rendering for Flask: http://flask.pocoo.org/docs/0.12/patterns/wtforms/
- [WTForms-Alchemy](https://wtforms-alchemy.readthedocs.io/en/latest/introduction.html#) allows to create forms based on sqlalchemy models

PS. I'm quite missing [rails generate scaffold](http://guides.rubyonrails.org/command_line.html#rails-generate), it was generating a lot of code in a second.

**Comment by KrzysztofMadejski** [comment]
Forms should be versioned along with logic that is processing them.

**Comment by KrzysztofMadejski** [comment]
We have finally based the solution on DjangoForm. Nothing gets generated, but you can define the form in code and then use a simple template to iterate through all fields.
