### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by IronRunes** [themoonsheep/moonsheep#72]
https://marvelapp.com/h9h3ch6/screen/28518092

Archived below:
![moonsheep-mockups-home](https://user-images.githubusercontent.com/849975/44145933-ab5a168a-a08d-11e8-87db-8df44e31bfa1.png)

![moonsheep-mockup1](https://user-images.githubusercontent.com/849975/44145899-91056e4c-a08d-11e8-88c4-fa72c2c9dcb7.png)
![moonsheep-mockup-campaign](https://user-images.githubusercontent.com/849975/44145904-93dafb3c-a08d-11e8-8fee-8f15857f48b9.png)
![moonsheep-clone-flow](https://user-images.githubusercontent.com/849975/44145906-956e6bfa-a08d-11e8-8abe-effd7ef49111.png)
![moonsheep-mockups-widets](https://user-images.githubusercontent.com/849975/44145909-9751a93c-a08d-11e8-922a-6355945f95d0.png)

**Comment by KrzysztofMadejski** [comment]
Mockups and designs by Ozren:
- landing page
- admin portal on 2nd page

https://projects.invisionapp.com/share/TYFAB0FEX#/screens/272917181_landing_Page
